import type { CSSProperties } from "react";

/** Co-located styles for SkillsTab. */
export const s = {
  wrap: { maxWidth: 680 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 16 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  saveRow: { display: "inline-flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  unsaved: { fontSize: 12, fontWeight: 600, color: "var(--warn)" } satisfies CSSProperties,
  savedOk: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--ok)",
  } satisfies CSSProperties,
  search: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-primary)",
    background: "transparent",
    border: "none",
    outline: "none",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (on: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: on ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: on ? 1 : 0.7,
    cursor: "pointer",
  }),
  grip: { color: "var(--text-muted)", cursor: "grab" } satisfies CSSProperties,
  checkbox: (on: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    borderRadius: 4,
    border: "1.5px solid " + (on ? "var(--accent)" : "var(--border-strong)"),
    background: on ? "var(--accent)" : "transparent",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  }),
  checkIcon: { color: "#fff" } satisfies CSSProperties,
  skillName: { fontSize: 13, fontWeight: 600, flex: 1 } satisfies CSSProperties,
  typeChip: (color: string): CSSProperties => ({
    fontSize: 12,
    fontWeight: 600,
    color,
    background: color + "1a",
    padding: "1px 8px",
    borderRadius: 4,
  }),
  searchIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
