import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard (extracted from inline styles). */
export const s = {
  card: (accepted: boolean, rejected: boolean): CSSProperties => ({
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${accepted ? "var(--ok)" : rejected ? "var(--crit)" : "var(--border)"}`,
    borderRadius: 9,
    background: "var(--bg-elevated)",
    padding: 18,
    marginBottom: 14,
    opacity: rejected ? 0.55 : 1,
  }),
  row: { display: "flex", gap: 16 } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rule: {
    fontSize: 15,
    fontWeight: 600,
    fontStyle: "italic",
    lineHeight: 1.4,
    textAlign: "left",
    background: "none",
    border: "none",
    color: "var(--text-primary)",
    cursor: "text",
    padding: 0,
    width: "100%",
  } satisfies CSSProperties,
  ruleInput: {
    fontSize: 15,
    fontWeight: 600,
    lineHeight: 1.4,
    width: "100%",
    background: "var(--bg-surface)",
    border: "1px solid var(--accent)",
    borderRadius: 6,
    color: "var(--text-primary)",
    padding: "6px 8px",
  } satisfies CSSProperties,
  category: {
    display: "inline-block",
    marginTop: 6,
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  } satisfies CSSProperties,
  evidence: { marginTop: 12, borderRadius: 7, border: "1px solid var(--border)", overflow: "hidden" } satisfies CSSProperties,
  evidenceHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 12px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  copyIcon: { color: "var(--text-muted)", cursor: "pointer" } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "12px 14px",
    fontSize: 12,
    lineHeight: 1.55,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
    overflow: "auto",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 12, marginTop: 12 } satisfies CSSProperties,
  confidenceLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  confidenceBar: { width: 90 } satisfies CSSProperties,
  confidenceValue: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  actionCol: { display: "flex", flexDirection: "column", gap: 8, flexShrink: 0, width: 150 } satisfies CSSProperties,
  acceptedBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--ok)",
    padding: "8px 0",
  } satisfies CSSProperties,
} as const;
