import type { CSSProperties } from "react";

export const s = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "64px 24px",
    zIndex: 50,
    overflowY: "auto",
  } satisfies CSSProperties,
  modal: {
    width: "100%",
    maxWidth: 720,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: "18px 22px 0",
  } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  close: { background: "none", border: "none", color: "var(--text-muted)", cursor: "pointer", padding: 4 } satisfies CSSProperties,
  banner: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    margin: "16px 22px 4px",
    padding: "10px 12px",
    borderRadius: 8,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  body: { padding: "8px 22px 4px", display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  field: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  label: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  req: { color: "var(--crit)" } satisfies CSSProperties,
  input: {
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "9px 11px",
    fontSize: 14,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  twoCol: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, alignItems: "end" } satisfies CSSProperties,
  toggleRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  editorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderBottom: "none",
    borderRadius: "8px 8px 0 0",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  editorFile: { display: "inline-flex", alignItems: "center", gap: 6, color: "var(--text-secondary)" } satisfies CSSProperties,
  unsaved: { fontSize: 10, padding: "1px 6px", borderRadius: 4, background: "var(--warn-bg)", color: "var(--warn)" } satisfies CSSProperties,
  textarea: {
    width: "100%",
    minHeight: 220,
    background: "var(--code-bg)",
    border: "1px solid var(--border)",
    borderRadius: "0 0 8px 8px",
    padding: "12px 14px",
    fontSize: 12.5,
    lineHeight: 1.55,
    color: "var(--text-primary)",
    resize: "vertical",
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 22px 18px",
    marginTop: 8,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerStatus: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  footerActions: { display: "flex", gap: 10 } satisfies CSSProperties,
  error: { color: "var(--crit)", fontSize: 13, margin: "0 22px" } satisfies CSSProperties,
} as const;
